# Generated by Django 5.1.6 on 2025-02-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='date_of_birth',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='person',
            name='product',
            field=models.CharField(choices=[('Пульс Тепло', 'Пульс Тепло'), ('Пульс счетчик воды 80й', 'Пульс счетчик воды 80й'), ('Пульс счетчик воды 110й', 'Пульс счетчик воды 110й'), ('Пломбы', 'Пломбы')], max_length=50),
        ),
    ]
