# Generated by Django 5.1.6 on 2025-02-06 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aliance', '0002_rename_date_of_birth_person_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Склад', 'verbose_name_plural': 'Склад'},
        ),
    ]
