# Generated by Django 5.1.6 on 2025-02-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliance', '0003_alter_person_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(choices=[('САО', 'САО'), ('ЮАО', 'ЮАО'), ('ЗАО', 'ЗАО'), ('ВАО', 'ВАО')], max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('flat', models.IntegerField()),
                ('phone', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('comment', models.TextField(max_length=100)),
                ('price', models.IntegerField()),
                ('uk', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склад',
            },
        ),
        migrations.AlterModelOptions(
            name='person',
            options={},
        ),
    ]
