# Generated by Django 5.1.6 on 2025-02-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliance', '0004_applications_alter_person_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='applications',
            options={'verbose_name': 'Заявки', 'verbose_name_plural': 'Заявки'},
        ),
    ]
